In [1]:
import pandas as pd

In [2]:
path = '/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/'

In [ ]:
# MIM DERIVED

In [27]:
d1_MIM = pd.read_csv(path+'seed_7/deseq_MIM1d_UTR_PCT_seed7.csv')

In [28]:
d1_MIM.head()

,query,ident_uniprot,MIS_1d_1,MIS_1d_2,MIS_1d_3,MIM_1d_1,MIM_1d_2,MIM_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01,Protein names
0,TRINITY_DN100164_c3_g1_i3,EGR1_DANRE,529,242,195,1244,1122,1725,902.072347,-2.387501,0.444850,-5.366985,8.006359e-08,1.160838e-04,XP_014053604.1,Early growth response protein
1,TRINITY_DN100270_c0_g1_i7,CP51A_MACFA^CYP51_DANRE,1393,523,1622,3602,4631,4163,2793.840101,-2.107843,0.420871,-5.008286,5.491699e-07,5.620847e-04,XP_013997770.1,lanosterol 14-alpha demethylase-like
2,TRINITY_DN101365_c10_g1_i1,RL32_ICTPU,0,0,2,165,115,132,78.064567,-8.046111,1.122325,-7.169149,7.546565e-13,3.819107e-09,XP_013989550.1,60S ribosomal protein L32-like
3,TRINITY_DN101700_c1_g1_i6,LADD_ONCMY,2021,2547,802,9598,6107,2526,4303.884814,-2.152705,0.556492,-3.868349,1.095746e-04,3.109734e-02,NP_001117041.1,Serum lectin isoform 1 (serum lectin isoform 1...
4,TRINITY_DN102197_c3_g5_i1,PL8L1_MOUSE,8,18,20,39,43,169,52.131890,-2.762218,0.683682,-4.040210,5.340337e-05,1.859060e-02,XP_014056035.1,cornifelin-like

In [5]:
d1_MIM = d1_MIM[d1_MIM['log2FoldChange'] > 0]

In [6]:
d1_MIM.head()

,query,ident_uniprot,MIS_8d_1,MIS_8d_2,MIS_8d_3,MIM_8d_1,MIM_8d_2,MIM_8d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01,Protein names
2,TRINITY_DN100259_c1_g3_i8,ILEU_BOVIN,70,181,142,26,21,31,73.080194,2.094979,0.473742,4.422191,9.770500e-06,5.554234e-03,XP_014024685.1,leukocyte elastase inhibitor-like
4,TRINITY_DN100644_c4_g1_i1,TNR14_MOUSE,52,146,172,1,9,6,57.573342,4.344768,0.656739,6.615670,3.698723e-11,1.253157e-07,XP_014002711.1,tumor necrosis factor receptor superfamily mem...
5,TRINITY_DN101831_c4_g1_i5,SPD2B_HUMAN^SPD2B_MOUSE,715,796,1296,164,274,174,529.630922,2.018131,0.298425,6.762602,1.355348e-11,5.218214e-08,XP_014053506.1,SH3 and PX domain-containing protein 2B-like i...
6,TRINITY_DN101887_c0_g2_i4,TRI25_MOUSE,16,125,53,6,12,6,32.969246,2.824885,0.752118,3.755906,1.727155e-04,4.487529e-02,XP_014063828.1,"nuclear factor 7, ovary-like isoform X1"
7,TRINITY_DN102187_c4_g2_i4,MX1_ONCMY,16,477,279,18,6,8,119.014875,4.280675,0.830599,5.153719,2.553705e-07,3.090056e-04,NP_001117162.1,Mx2 protein (myxovirus resistance 2)

In [7]:
d1_INH_deseq = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/INH_deseq/8d_MIS_vs_INH_DESEQ_annotated.csv', low_memory=False)

In [8]:
d1_INH_deseq = d1_INH_deseq[d1_INH_deseq['log2FoldChange'] < 0]

In [9]:
d1_INH_deseq.head()

,trinity,ident_uniprot,MIS_8d_1,MIS_8d_2,MIS_8d_3,INH_8d_1,INH_8d_2,INH_8d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01
2,TRINITY_DN100001_c2_g2_i2,CIO1B_SALSA,1019,1089,1135,975,1189,1182,1092.237857,-0.352985,0.260964,-1.352620,0.176177,0.999967,XP_014027367.1
3,TRINITY_DN100001_c2_g2_i7,CIO1B_SALSA,309,394,412,335,382,267,345.498318,-0.149676,0.313667,-0.477180,0.633234,0.999967,XP_014015694.1
4,TRINITY_DN100001_c2_g3_i3,CIO1B_SALSA,382,375,456,457,419,336,406.984741,-0.345877,0.340241,-1.016565,0.309360,0.999967,XP_014027367.1
9,TRINITY_DN100004_c4_g1_i4,FOXP1_CHICK,3,2,2,0,6,1,2.125301,-0.072378,1.776189,-0.040749,0.967496,NaN,XP_013988543.1
10,TRINITY_DN100004_c4_g1_i7,FOXP1_CHICK^FOXP4_HUMAN,68,71,73,48,64,87,67.492053,-0.201480,0.405778,-0.496528,0.619522,0.999967,XP_014022296.1

In [10]:
d1_INH_deseq_filtered_by_MIM = d1_INH_deseq.loc[d1_INH_deseq['XP_01'].isin(d1_MIM['XP_01'])]

In [11]:
d1_INH_deseq_filtered_by_MIM.shape

(326, 15)

In [12]:
d1_INH_deseq_filtered_by_MIM_dup_drop = d1_INH_deseq_filtered_by_MIM.sort_values('padj', ascending=True).drop_duplicates('XP_01').sort_index()

In [13]:
d1_INH_deseq_filtered_by_MIM_dup_drop.sort_values('padj', ascending=True, inplace=True)

In [14]:
d1_INH_deseq_filtered_by_MIM_dup_drop.to_csv(path+"test.csv", index=False)

In [15]:
kandydaty_1d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_1d.csv')
kandydaty_6d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_6d.csv')
kandydaty_8d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_8d.csv')

In [20]:
wspolne_1d_6d = kandydaty_6d.loc[kandydaty_6d['XP_01'].isin(kandydaty_8d['XP_01'])]

In [21]:
wspolne_1d_6d

Empty DataFrame
Columns: [trinity, ident_uniprot, MIS_6d_1, MIS_6d_2, MIS_6d_3, INH_6d_1, INH_6d_2, INH_6d_3, baseMean, log2FoldChange, lfcSE, stat, pvalue, padj, XP_01, Protein names, Gene names, Organism, Length, Gene ontology (cellular component), Gene ontology (biological process), Gene ontology (molecular function)]
Index: []

[0 rows x 22 columns]

In [3]:
from bioinfokit import analys, visuz

In [5]:
df = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_MIM8d_UTR_PCT_seed7_MIM_derived_added.csv')
df_fc = df[df['log2FoldChange'] > 0]
MIM = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_8d.csv') 
df_fc = df_fc.loc[df_fc['XP_01'].isin(MIM['XP_01'])] 
df_fc.to_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_MIM8d_UTR_PCT_seed7_MIM_derived_added.csv', index=False)

In [18]:
df_volcano = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_MIM8d_UTR_PCT_seed7_MIM_derived_added.csv')

In [19]:
visuz.gene_exp.volcano(d=df_volcano, lfc='log2FoldChange', pv='padj', pv_thr=1, geneid="XP_01", genenames=({"XP_014011222.1":"1", "XP_014002711.1":"2", "XP_013994254.1":"3", "XP_013985637.1":"4", "XP_014068101.1":"5", "XP_013994513.1":"6"}), gstyle=1, valpha=0.5, xlm=(-15,11,5), ylm=(0,31, 10))

In [ ]:
#INH DERIVED

In [3]:
d1_INH = pd.read_csv(path+'seed_7/deseq_INH8d_UTR_PCT_seed7.csv')

In [4]:
d1_INH = d1_INH[d1_INH['log2FoldChange'] < 0]

In [5]:
d1_MIM_deseq = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/MIM_deseq/8d_MIS_vs_MIM_DESEQ_annotated.csv', low_memory=False)

In [6]:
d1_MIM_deseq = d1_MIM_deseq[d1_MIM_deseq['log2FoldChange'] > 0]

In [7]:
d1_MIM_deseq_filtered_by_INH = d1_MIM_deseq.loc[d1_MIM_deseq['XP_01'].isin(d1_INH['XP_01'])]

In [8]:
d1_MIM_deseq_filtered_by_INH.shape

(946, 15)

In [9]:
d1_MIM_deseq_filtered_by_INH_dup_drop = d1_MIM_deseq_filtered_by_INH.sort_values('padj', ascending=True).drop_duplicates('XP_01').sort_index()

In [10]:
d1_MIM_deseq_filtered_by_INH_dup_drop.sort_values('padj', ascending=True, inplace=True)

In [11]:
d1_MIM_deseq_filtered_by_INH_dup_drop.to_csv(path+"test.csv", index=False)

In [15]:
kandydaty_1d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_1d.csv')
kandydaty_6d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_6d.csv')
kandydaty_8d = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/MIM_derived_targets_8d.csv')

In [20]:
wspolne_1d_6d = kandydaty_6d.loc[kandydaty_6d['XP_01'].isin(kandydaty_8d['XP_01'])]

In [21]:
wspolne_1d_6d

Empty DataFrame
Columns: [trinity, ident_uniprot, MIS_6d_1, MIS_6d_2, MIS_6d_3, INH_6d_1, INH_6d_2, INH_6d_3, baseMean, log2FoldChange, lfcSE, stat, pvalue, padj, XP_01, Protein names, Gene names, Organism, Length, Gene ontology (cellular component), Gene ontology (biological process), Gene ontology (molecular function)]
Index: []

[0 rows x 22 columns]

In [3]:
from bioinfokit import analys, visuz

In [4]:
df = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_INH8d_UTR_PCT_seed7_INH_derived_added.csv')
df_fc = df[df['log2FoldChange'] < 0]
INH = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/INH_derived_targets_8d.csv') 
df_fc = df_fc.loc[df_fc['XP_01'].isin(INH['XP_01'])] 
df_fc.to_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_INH8d_UTR_PCT_seed7_INH_derived_added.csv', index=False)

In [5]:
change_sign = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_INH8d_UTR_PCT_seed7_INH_derived_added.csv')
change_sign['log2FoldChange'] = change_sign.log2FoldChange.multiply(-1)
change_sign.to_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_INH8d_UTR_PCT_seed7_INH_derived_added.csv')

In [13]:
df_volcano = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_INH_UP_MIM_DOWN/volcano_files/deseq_INH8d_UTR_PCT_seed7_INH_derived_added.csv')

In [14]:
visuz.gene_exp.volcano(d=df_volcano, lfc='log2FoldChange', pv='padj', pv_thr = 0.5, geneid="XP_01", genenames=({"XP_014066886.1":"1", "XP_013979251.1":"2", "XP_014051852.1":"3", "XP_014045325.1":"4", "XP_014049727.1":"5", "XP_014062994.1":"6"}), gstyle=1, valpha=0.5, xlm=(-15,11,5), ylm=(0,31, 10))

In [ ]:
# PBS vs MIM deseq -> porównanie z lista MIM vs INH

In [3]:
INH_MIM_deseq = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/1d_INH_vs_MIM_DESEQ.csv')

PBS_MIM_lfc = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_DESEQ_PBS_vs_MIM/1d_deseq_PBS_MIM_lfc_pval.csv')

In [6]:
wspolne = PBS_MIM_lfc.loc[PBS_MIM_lfc['ident_salmo'].isin(INH_MIM_deseq['ident_salmo'])]

In [7]:
wspolne

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_1d_1,MIM_1d_2,MIM_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo,Unnamed: 16,Unnamed: 17
7,TRINITY_DN87679_c7_g1_i3,63,35,37,34,0,1,0,22.436977,"6,67383365634287",1.303374,5.120428,3.048436e-07,"0,000839453484451",NaN,XP_014010562.1,NaN,NaN
8,TRINITY_DN94548_c5_g5_i1,436,469,316,1431,43,157,46,377.751219,"2,85266037731351",0.573106,4.977548,6.439496e-07,"0,001384004730699",NaN,XP_013979251.1,NaN,NaN
39,TRINITY_DN103280_c1_g4_i1,1038,1623,1788,129,134,187,113,687.550780,"2,82749666905033",0.659367,4.288196,1.801303e-05,"0,010791294701693",AMBP_PLEPL,XP_013994225.1,NaN,NaN
41,TRINITY_DN108631_c1_g3_i3,230,364,28,25,9,12,16,88.434569,"3,47612179353733",0.829721,4.189508,2.795596e-05,"0,014192102250946",NaN,XP_014041094.1,NaN,NaN
53,TRINITY_DN96540_c3_g9_i1,136,61,33,105,7,25,9,49.192702,"2,44004893447591",0.609425,4.003855,6.231870e-05,"0,023960721026564",NaN,XP_014019192.1,NaN,NaN
66,TRINITY_DN97983_c7_g1_i3,38,34,67,4,0,3,2,20.385169,"4,34149364541426",1.105397,3.927543,8.581807e-05,"0,02891953008753",NaN,XP_014038698.1,NaN,NaN
77,TRINITY_DN106365_c6_g2_i5,96,79,73,5,3,0,8,35.557688,"3,89280869766256",1.010839,3.851067,1.176043e-04,"0,034756932672465",MANS1_MACFA,XP_014038697.1,NaN,NaN
87,TRINITY_DN101307_c2_g2_i2,33,325,363,13,9,7,26,107.648877,"3,56936256579189",0.946021,3.773026,1.612793e-04,"0,042233822743798",NaN,XP_013994225.1,XP_013994226.1,NaN
91,TRINITY_DN89469_c3_g1_i2,1947,386,514,1892,123,297,306,719.848382,"2,10279355558613",0.563294,3.733030,1.891903e-04,"0,046298249457389",NaN,XP_014012275.1,NaN,NaN
93,TRINITY_DN102984_c3_g1_i4,713,899,611,1386,90,363,328,583.739798,"1,64017902536368",0.440600,3.722602,1.971804e-04,"0,047400839884215",CERS2_BOVIN,XP_013982992.1,NaN,NaN

In [14]:
wspolne3 = PBS_INH_lfc.loc[PBS_INH_lfc['ident_salmo'].isin(INH_MIM_deseq['ident_salmo'])]
wspolne3

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,INH_1d_1,INH_1d_2,INH_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo,Unnamed: 16,Unnamed: 17
6,TRINITY_DN86556_c13_g1_i1,0,3,13,1,162,215,330,104.985217,"-5,79245582639204",0.803415,-7.209795,5.603615e-13,"6,90E-09",NaN,XP_014043980.1,NaN,NaN
57,TRINITY_DN99375_c2_g2_i1,6,8,8,8,39,36,29,19.102698,"-2,27875531762802",0.549618,-4.146070,3.382299e-05,"0,025063345259075",NaN,XP_013979251.1,NaN,NaN
65,TRINITY_DN114100_c5_g2_i3,4,2,2,0,23,28,18,11.031778,"-3,59195416087451",0.882261,-4.071306,4.675020e-05,"0,030716440110751",TC1A_CAEEL,NP_001133228.1,NaN,NaN

In [8]:
PBS_INH_lfc = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_DESEQ_PBS_vs_MIM/1d_deseq_PBS_INH_lfc_pval.csv')

In [11]:
wspolne2 = PBS_INH_lfc.loc[PBS_INH_lfc['ident_salmo'].isin(PBS_MIM_lfc['ident_salmo'])]

In [12]:
wspolne2

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,INH_1d_1,INH_1d_2,INH_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo,Unnamed: 16,Unnamed: 17
24,TRINITY_DN106163_c3_g1_i6,39,110,38,67,300,230,242,145.502596,"-2,1142567763592",0.421358,-5.017720,5.228831e-07,"0,001120276940689",AATC_CHICK,NP_001135211.1,NaN,NaN
39,TRINITY_DN101177_c0_g1_i6,8,7,4,8,24,32,136,31.692679,"-3,35385484453483",0.737357,-4.548481,5.403460e-06,"0,006656724440689",AATM_MOUSE,XP_013982475.1,NaN,NaN
57,TRINITY_DN99375_c2_g2_i1,6,8,8,8,39,36,29,19.102698,"-2,27875531762802",0.549618,-4.146070,3.382299e-05,"0,025063345259075",NaN,XP_013979251.1,NaN,NaN

In [ ]:
# FCK XP_; identyfikacja po trinity

In [17]:
rnahyb_out = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/output_PCT_UTR_sklejone_razem.csv')

In [76]:
# DESEQ PBS (1d) vs. MIM (1d)

d1_deseq_PBS_MIM = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_DESEQ_PBS_vs_MIM/1d_PBS_vs_MIM_DESEQ_lfc_pval.csv')

In [77]:
wspolne4 = d1_deseq_PBS_MIM.loc[d1_deseq_PBS_MIM['trinity'].isin(rnahyb_out['trinity'])]

In [78]:
wspolne4

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_1d_1,MIM_1d_2,MIM_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo,Unnamed: 16,Unnamed: 17
0,TRINITY_DN89160_c5_g2_i1,1815,161,1224,430,21,27,24,500.815165,"5,0727097551863",0.675081,7.514228,5.724775e-14,"5,04E-09",CALL4_BOVIN,NP_001134348.1,NaN,NaN
6,TRINITY_DN88591_c4_g3_i3,25598,4662,5635,27915,1998,1160,534,8811.842301,"3,38042688742018",0.657557,5.140891,2.734392e-07,"0,000809415780231",PCKGC_RAT^PCKGC_CHICK,NP_001133921.1,NaN,NaN
9,TRINITY_DN88591_c4_g3_i4,40811,7392,6586,36456,2979,1783,798,12619.775750,"3,30502469703352",0.666003,4.962480,6.959887e-07,"0,001426275141815",PCKGC_MOUSE^PCKGC_CHICK,NP_001133921.1,NaN,NaN
10,TRINITY_DN80500_c10_g1_i1,22,41,50,167,4,5,2,38.149923,"4,03231686215492",0.824250,4.892107,9.976227e-07,"0,001870415113793",SUCA_CAEEL,XP_014051070.1,NaN,NaN
15,TRINITY_DN94078_c3_g1_i1,77,105,96,28,8,12,8,45.240361,"2,8632621830562",0.603113,4.747470,2.059774e-06,"0,003129399744851",THOC7_BOVIN,NP_001134956.1,NaN,NaN
22,TRINITY_DN85707_c12_g4_i1,1736,4393,2956,3247,276,1219,414,1901.652458,"2,1585157035976",0.473386,4.559741,5.121687e-06,"0,005196102745515",NaN,XP_013987820.1,NaN,NaN
31,TRINITY_DN98719_c2_g1_i6,136,67,174,93,17,14,32,73.252097,"2,3062600140463",0.531552,4.338732,1.433072e-05,"0,009865692774187",MAP9_HUMAN^MAP9_MOUSE,XP_014051024.1,NaN,NaN
35,TRINITY_DN98719_c2_g1_i16,115,60,155,101,6,14,31,65.720774,"2,52480560170869",0.584146,4.322214,1.544711e-05,"0,010158087248741",MAP9_MOUSE^MAP9_HUMAN,XP_014051026.1,XP_014051024.1,NaN
39,TRINITY_DN103280_c1_g4_i1,1038,1623,1788,129,134,187,113,687.550780,"2,82749666905033",0.659367,4.288196,1.801303e-05,"0,010791294701693",AMBP_PLEPL,XP_013994225.1,NaN,NaN
47,TRINITY_DN90037_c8_g1_i1,23,31,51,30,4,0,4,19.572906,"3,43968188197065",0.841141,4.089307,4.326640e-05,"0,018689177025471",WNT4_CHICK,XP_014009267.1,NaN,NaN
56,TRINITY_DN85239_c0_g2_i1,43,69,54,108,6,22,3,40.340616,"2,57605793573137",0.646686,3.983477,6.791422e-05,"0,0251733197579",NaN,XP_014068297.1,NaN,NaN
64,TRINITY_DN104372_c5_g2_i2,185,355,3,24,3,13,5,75.097666,"4,15407546958405",1.054146,3.940703,8.124318e-05,"0,028074776853301",NaN,XP_014062994.1,NaN,NaN
71,TRINITY_DN107524_c4_g5_i1,40,94,7,218,10,2,4,48.115584,"3,71446725769975",0.949263,3.913002,9.115574e-05,"0,029696763744435",PFKAP_RAT,XP_014045825.1,XP_013995008.1,NaN
75,TRINITY_DN108505_c2_g1_i9,11971,5158,3769,26670,1690,3359,1387,7057.954790,"2,25833593363619",0.583223,3.872168,1.078716e-04,"0,032891142613304",UCP3_CANLF^UCP2_DANRE^UCP3_MOUSE,XP_014064971.1,NaN,NaN
82,TRINITY_DN85707_c12_g1_i2,793,1425,797,2503,210,580,322,878.318838,"1,7213165678086",0.453324,3.797097,1.464007e-04,"0,039645351027879",NaN,XP_013987820.1,NaN,NaN
89,TRINITY_DN111264_c2_g2_i25,104,254,145,253,38,13,61,116.514083,"2,08291853625929",0.554268,3.757964,1.713017e-04,"0,043753421971422",BMAL2_CHICK,XP_014063876.1,XP_014009050.1,NaN
94,TRINITY_DN107870_c0_g3_i1,88,101,103,110,20,45,38,68.489953,"1,38322981051137",0.371630,3.722063,1.976018e-04,"0,047400839884215",IKZF5_HUMAN,XP_014007463.1,NaN,NaN
96,TRINITY_DN99897_c4_g1_i7,82,88,78,171,18,42,28,67.766566,"1,65625552011478",0.446796,3.706958,2.097638e-04,"0,049055215003904",DGKB_HUMAN,XP_014020649.1,XP_014020625.1,NaN

In [79]:
# DESEQ PBS (1d) vs. INH (1d)

d1_deseq_PBS_INH = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/seed_7/Metodyka_DESEQ_PBS_vs_MIM/1d_PBS_vs_INH_DESEQ_lfc_pval.csv')

In [80]:
wspolne5 = d6_deseq_PBS_INH.loc[d6_deseq_PBS_INH['trinity'].isin(rnahyb_out['trinity'])]

In [81]:
wspolne5

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,INH_6d_1,INH_6d_2,INH_6d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo
3,TRINITY_DN99876_c4_g1_i6,300,405,328,328,2297,1906,1988,1077.829333,"-2,66804349526883",0.233851,-11.409158,3.763548e-30,"6,81E-26",FABP7_BOVIN,NP_001243886.1
11,TRINITY_DN99876_c4_g1_i2,449,527,519,559,3359,2600,5102,1855.248206,"-2,89140724881371",0.282542,-10.233549,1.402827e-24,"1,02E-20",FABP7_BOVIN,NP_001135371.1
22,TRINITY_DN99544_c4_g1_i4,0,2,3,0,121,182,173,69.161066,"-7,04477155043626",0.772974,-9.113850,7.950890e-20,"2,40E-16",N42L1_MOUSE,XP_013985205.1
23,TRINITY_DN99544_c4_g1_i3,4,1,4,0,101,184,161,65.472848,"-6,09943987630668",0.675104,-9.034815,1.642798e-19,"4,79E-16",N42L1_MOUSE,XP_013985205.1
34,TRINITY_DN99082_c3_g3_i2,328,356,286,384,1257,1275,1058,703.283041,"-1,90061985135508",0.227166,-8.366668,5.927051e-17,"1,12E-13",PR3CB_DANRE,XP_014013818.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,TRINITY_DN91235_c0_g2_i2,23,18,25,2,80,52,65,37.879536,"-1,98338673359301",0.670455,-2.958269,3.093719e-03,"0,047917153901027",ADAP1_HUMAN,XP_014013897.1
2817,TRINITY_DN96275_c1_g1_i10,5,12,3,12,45,27,19,17.466794,"-2,02994041837161",0.686255,-2.957998,3.096436e-03,"0,047926414249789",PTN7_HUMAN,NP_001167320.1
2849,TRINITY_DN77779_c0_g1_i1,367,410,315,145,1244,705,402,512.543174,"-1,41709714228958",0.481024,-2.946000,3.219125e-03,"0,049213789141586",GPX1_PIG^CC062_MOUSE,XP_013989347.1
2851,TRINITY_DN111078_c5_g2_i6,12,28,26,12,27,131,54,41.794197,"-1,92460130230044",0.653646,-2.944410,3.235707e-03,"0,04941142038785",NaN,XP_013996563.1
2859,TRINITY_DN104456_c1_g2_i4,12,49,16,3,264,106,10,66.690112,"-2,76924251877917",0.941843,-2.940239,3.279594e-03,"0,049898921402611",LRRN3_PONAB,XP_014003620.1^XP_013981039.1

In [26]:
# DESEQ PBS (1d) vs. MIM (6d)

d6_deseq_PBS_MIM = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/6d_PBS_vs_MIM_DESEQ_lfc_pval.csv')

In [28]:
d6_deseq_PBS_MIM.shape

(2063, 16)

In [29]:
wspolne7 = d6_deseq_PBS_MIM.loc[d6_deseq_PBS_MIM['trinity'].isin(rnahyb_out['trinity'])]
wspolne7

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_6d_1,MIM_6d_2,MIM_6d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo
2,TRINITY_DN88591_c4_g3_i4,40811,7392,6586,36456,104,349,424,12837.689396,"6,26676363011105",0.687947,9.109369,8.286215e-20,"1,82E-15",PCKGC_MOUSE^PCKGC_CHICK,NP_001133921.1
4,TRINITY_DN88591_c4_g3_i3,25598,4662,5635,27915,100,272,372,9012.743746,"5,99247059142846",0.667377,8.979142,2.728854e-19,"4,80E-15",PCKGC_RAT^PCKGC_CHICK,NP_001133921.1
28,TRINITY_DN98538_c0_g2_i2,189,167,177,314,17,27,38,131.823612,"2,98525237608861",0.433834,6.881090,5.939642e-12,"1,27E-08",SAMTR_DANRE,XP_013981036.1
37,TRINITY_DN103768_c1_g3_i1,17929,14871,16399,20174,4704,6556,4843,12128.609006,"1,74781313940631",0.265767,6.576494,4.816691e-11,"7,57E-08",GCSP_MOUSE,XP_014027021.1
41,TRINITY_DN108505_c2_g1_i9,11971,5158,3769,26670,929,1061,625,6963.262963,"3,79883807357744",0.582023,6.526957,6.711952e-11,"9,84E-08",UCP3_CANLF^UCP2_DANRE^UCP3_MOUSE,XP_014064971.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2038,TRINITY_DN107891_c3_g2_i5,111,76,55,96,36,47,24,62.342358,"1,29636733236226",0.416660,3.111335,1.862436e-03,"0,049155760401807",LGAT1_MOUSE,XP_013999458.1
2048,TRINITY_DN114252_c0_g1_i4,3010,2469,1874,3075,1351,1779,1391,2097.710171,"0,833817344520449",0.268257,3.108281,1.881789e-03,"0,049356842899318",UCRI_AOTAZ,XP_013981996.1^XP_014031036.1
2050,TRINITY_DN102641_c5_g1_i32,272,230,126,401,49,130,97,182.637228,"1,49061470386945",0.479694,3.107426,1.887245e-03,"0,049411546645844",CMC1_HUMAN,XP_013996365.1
2052,TRINITY_DN109684_c2_g7_i1,66,57,32,48,28,14,16,36.444647,"1,45957962565897",0.469800,3.106812,1.891163e-03,"0,049448784723358",NaN,XP_013999477.1
2058,TRINITY_DN100852_c6_g1_i4,3020,4901,2683,5129,1395,2653,943,2903.292177,"1,28270840714427",0.413227,3.104123,1.908442e-03,"0,049729735106551",CDO1_DANRE,XP_014016430.1

In [35]:
wspolne_MIM_d1_d6 = wspolne7.loc[wspolne7['trinity'].isin(wspolne4['trinity'])]
wspolne_MIM_d1_d6.shape

(8, 16)

In [36]:
wspolne_MIM_d1_d6 # wspolne dla deseq PBS vs MIM1d i PBS vs MIM6d trinity z miejscem wiazania 92b (seed7)

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_6d_1,MIM_6d_2,MIM_6d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo
2,TRINITY_DN88591_c4_g3_i4,40811,7392,6586,36456,104,349,424,12837.689396,"6,26676363011105",0.687947,9.109369,8.286215e-20,"1,82E-15",PCKGC_MOUSE^PCKGC_CHICK,NP_001133921.1
4,TRINITY_DN88591_c4_g3_i3,25598,4662,5635,27915,100,272,372,9012.743746,"5,99247059142846",0.667377,8.979142,2.728854e-19,"4,80E-15",PCKGC_RAT^PCKGC_CHICK,NP_001133921.1
41,TRINITY_DN108505_c2_g1_i9,11971,5158,3769,26670,929,1061,625,6963.262963,"3,79883807357744",0.582023,6.526957,6.711952e-11,"9,84E-08",UCP3_CANLF^UCP2_DANRE^UCP3_MOUSE,XP_014064971.1
56,TRINITY_DN85707_c12_g1_i2,793,1425,797,2503,96,146,244,841.885605,"3,0925227197299",0.500186,6.182740,6.299842e-10,"6,76E-07",NaN,XP_013987820.1
92,TRINITY_DN85707_c12_g4_i1,1736,4393,2956,3247,294,799,455,1974.404295,"2,61586241566472",0.447860,5.840802,5.195009e-09,"3,66E-06",NaN,XP_013987820.1
596,TRINITY_DN89160_c5_g2_i1,1815,161,1224,430,58,177,130,581.801864,"2,96312443278602",0.717264,4.131152,3.609505e-05,"0,003547841081219",CALL4_BOVIN,NP_001134348.1
698,TRINITY_DN107870_c0_g3_i1,88,101,103,110,56,26,27,72.180443,"1,56105517864702",0.389854,4.004201,6.222755e-05,"0,005197300896495",IKZF5_HUMAN,XP_014007463.1
1927,TRINITY_DN85239_c0_g2_i1,43,69,54,108,22,34,13,48.214661,"1,62856337413193",0.515786,3.157437,1.591625e-03,"0,044819735099312",NaN,XP_014068297.1

In [37]:
# DESEQ PBS (1d) vs. MIM (8d)

d8_deseq_PBS_MIM = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/8d_PBS_vs_MIM_DESEQ_lfc_pval.csv')

In [38]:
wspolne8 = d8_deseq_PBS_MIM.loc[d8_deseq_PBS_MIM['trinity'].isin(rnahyb_out['trinity'])] 
wspolne8.shape

(335, 16)

In [39]:
wspolne_MIM_d1_d8 = wspolne8.loc[wspolne8['trinity'].isin(wspolne_MIM_d1_d6['trinity'])]
wspolne_MIM_d1_d8.shape

(1, 16)

In [40]:
wspolne_MIM_d1_d8 # wspolne dla deseq PBS vs MIM1d i PBS vs MIM6d i PBS vs MIM8d trinity z miejscem wiazania 92b (seed7)

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_8d_1,MIM_8d_2,MIM_8d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo
561,TRINITY_DN108505_c2_g1_i9,11971,5158,3769,26670,4205,2336,821,7334.822934,"2,08448230909432",0.653796,3.188279,0.001431,"0,036658190740115",UCP3_CANLF^UCP2_DANRE^UCP3_MOUSE,XP_014064971.1

In [41]:
# DESEQ PBS (1d) vs. INH (6d)

d6_deseq_PBS_INH = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/6d_PBS_vs_INH_DESEQ_lfc_pval.csv')

In [43]:
wspolne9 = d6_deseq_PBS_INH.loc[d6_deseq_PBS_INH['trinity'].isin(rnahyb_out['trinity'])] 
wspolne9.shape

(425, 16)

In [51]:
# DESEQ PBS (1d) vs. INH (8d)

d8_deseq_PBS_INH = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/8d_PBS_vs_INH_DESEQ_lfc_pval.csv')

In [52]:
wspolne10 = d8_deseq_PBS_INH.loc[d8_deseq_PBS_INH['trinity'].isin(rnahyb_out['trinity'])]
wspolne10.shape

(224, 16)

In [44]:
# po INH nie ma wspolnych trinity z miejscem wiazania 92b w dniach 1 i 6
wspolne_INH_d1_d6 = wspolne9.loc[wspolne9['trinity'].isin(PBS_MIM_lfc['trinity'])]
wspolne_INH_d1_d6.shape

(0, 16)

In [ ]:
# czy sa wspolne 1)_trinity_ oraz 2)_XP_ w MIM i INH z miejscem wiazania 92b po:
# MIM  INH
# 1d - 1d
# 1d - 6d
# 1d - 8d
# 6d - 6d
# 6d - 8d
# 8d - 8d

In [72]:
# 1d - 1d
wspolne_MIM_1d_INH_1d = wspolne4[wspolne4['trinity'].isin(wspolne5['trinity'])]
wspolne_MIM_1d_INH_1d.shape

(0, 20)

In [73]:
# 1d - 6d
wspolne_MIM_1d_INH_6d = wspolne4[wspolne4['trinity'].isin(wspolne9['trinity'])]
wspolne_MIM_1d_INH_6d.shape

(0, 20)

In [53]:
# 1d - 8d
wspolne_MIM_1d_INH_8d = wspolne4[wspolne4['trinity'].isin(wspolne10['trinity'])]
wspolne_MIM_1d_INH_8d.shape

(0, 18)

In [58]:
# 6d - 6d
wspolne_MIM_6d_INH_6d = wspolne7[wspolne7['trinity'].isin(wspolne9['trinity'])]
wspolne_MIM_6d_INH_6d.shape

(0, 16)

In [59]:
# 6d - 8d
wspolne_MIM_6d_INH_8d = wspolne7[wspolne7['trinity'].isin(wspolne10['trinity'])]
wspolne_MIM_6d_INH_8d.shape

(0, 16)

In [61]:
# 8d - 8d
wspolne_MIM_8d_INH_8d = wspolne8[wspolne8['trinity'].isin(wspolne10['trinity'])]
wspolne_MIM_8d_INH_8d.shape

(0, 16)

In [74]:
wspolne_MIM_1d_INH_1d = wspolne4[wspolne4['ident_salmo'].isin(wspolne5['ident_salmo'])]
wspolne_MIM_1d_INH_1d.shape

(4, 20)

In [75]:
wspolne_MIM_1d_INH_1d

,trinity,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MIM_1d_1,MIM_1d_2,MIM_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
65,TRINITY_DN104372_c5_g2_i2,185,355,3,24,3,13,5,75.097666,"4,15407546958405",1.054146,3.940703,0.000081,"0,028074776853301",NaN,XP_014062994.1,NaN,NaN,NaN,NaN
426,TRINITY_DN90597_c4_g1_i1,40,119,47,152,26,32,16,57.611392,"1,62381588780712",0.569602,2.850791,0.004361,"0,268548159611296",ID2_BOVIN^ID2_HUMAN,NP_001134882.1,NaN,NaN,NaN,NaN
539,TRINITY_DN82863_c2_g4_i1,140,80,179,632,64,78,65,165.748845,"1,67696433158101",0.617495,2.715752,0.006613,"0,334767655544489",NaN,XP_013994254.1,NaN,NaN,NaN,NaN
770,TRINITY_DN79637_c4_g2_i2,28,6,2,22,0,1,3,7.987397,"3,23506005049777",1.291946,2.504021,0.012279,"0,457603055931501",NaN,XP_014043121.1,NaN,NaN,NaN,NaN